#spring.application.name=demo
#server.port=${SERVER_PORT:8080}

# URL de conexión (se obtiene del archivo .env)
#spring.datasource.url=${DB_URL}

# Credenciales de acceso (se obtienen del archivo .env)
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASS}

# Indica que el driver a usar es el de PostgreSQL
#spring.datasource.driver-class-name=org.postgresql.Driver

# Mantiene la tabla actualizada según las clases de Java
#spring.jpa.hibernate.ddl-auto=update

# Permite ver en la consola las consultas que Java hace a la nube
#spring.jpa.show-sql=true



spring.application.name=demo
server.port=8080

spring.datasource.url=jdbc:postgresql://ep-sparkling-dawn-ageup1rq-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_vJy6uCUrxaH9

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true